version: "3.8"
name: goals-app
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    env_file:
      - ./env/mongo.env
    volumes:
      - data:/data/db

  goals-backend-app:
    build: ./backend
    container_name: goals-backend-app
    env_file:
      - ./env/backend.env
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    ports:
      - "80:80"
    depends_on:
      - mongodb

  goals-frontend-app:
    build: ./frontend
    container_name: goals-frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - goals-backend-app

volumes:
  data:
  logs:
