version: "3.8"
name: goals-app
services:
  mongo-db:
    image: mongo:7.0.5
    container_name: mongo-db
    env-file:
      - ./env/mongo.env
    volumes:
      - data:/data/db
    networks:
      - goals-net

  goals-backend-app:
    build: ./backend
    container_name: goals-backend-app
    env-file:
      - ./env/backend.env
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    ports:
      - "80:80"
    networks:
      - goals-net
    depends_on:
      - mongo-db

  goals-frontend-app:
    build: ./frontend
    container_name: goals-frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - goals-net
    depends_on:
      - goals-backend-app

volumes:
  data:
  logs:

networks:
  goals-net: